### ISSUE TITLE
1.0.1 tag

### ISSUE THREAD

**Issue by afhole** [lindenbaum/glob#1]
Is 1.0.1 ready for release/tagging?

Thanks for the great library :)

**Comment by schlagert** [comment]
We're always glad, if our stuff is useful for others!

To your question: There is currently no need to release 1.0.1 since there is no difference to the 1.0.0 release. The 1.0.1 version only got bumped after the 1.0.0 release for further development.

**Comment by afhole** [comment]
Ah I see, thanks :)
